# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('quiz', '0006_auto_20181129_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Songs'),
        ),
    ]
