# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-05 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='dynamic_table',
            field=models.IntegerField(blank=True, choices=[(0, 'SHIPPER'), (1, 'TRANSPORTER'), (2, 'FORWARDER')], null=True),
        ),
    ]
