# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-10 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stakeholder', '0002_auto_20181205_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hubs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=64)),
                ('stakeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stakeholder.Stakeholder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
